import {FlatTreeControl} from '@angular/cdk/tree';
import {Component, Injectable, Output, EventEmitter, Input} from '@angular/core';
import {MatTreeFlatDataSource, MatTreeFlattener} from '@angular/material/tree';
import {BehaviorSubject, Observable, of as observableOf} from 'rxjs';
import { NgForm } from '@angular/forms';
export class FileNode {
   children: FileNode[];
   filename: string;
   type: any;
}
export class FileFlatNode {
   constructor(
      public expandable: boolean, public filename: string, public level: number, public type: any) {}
}
const TREE_DATA = JSON.stringify({
   "CEG:": {
		"University Admin": {
			"OFFICE OF THE VICE-CHANCELLOR": {
				"Vice-Chancellor": "ts",
				"PS to VC": "ts",
				"Steno to VC": "ts",
				"VCís Office": "ts"
			},
			"OFFICE  OF THE REGISTRAR": {
				"Registrar": "ts",
				"PA to Registrar": "ts"
			},
			"OFFICERS OF THE CONTROLLER OF EXAMINATIONS (AFF. COLLEGES)": {
				"COE": "ts",
				"ACOE ñ I": "ts",
				"ACOE ñ II": "ts",
				"ACOE (Zones)": "ts",
				"Deputy Controller, Distance Education": "ts"
			},
			"OFFICERS OF THE ADDITIONAL CONTROLLER OF EXAMINATIONS (UNIV. DEPTS)": {
				"Addl. Controller (CEG)": "ts",
				"Deputy Controller (CEG)": "ts",
				"Deputy Controller (ACT)": "ts",
				"Deputy Controller (SAP)": "ts",
				"Deputy Controller (MIT)": "ts"
			},
			"DEANS  OF CAMPUSES": {
				"Dean,CEG": "ts",
				"Dean,ACT": "ts",
				"Dean, MIT": "ts",
				"Dean,SAP": "ts"
			},
			"FACULTY CHAIRPERSONS": {
				"Faculty of Civil Engineering": "ts",
				"Faculty of Mechanical Engineering": "ts",
				"Faculty of Electrical Engineering": "ts",
				"Faculty of Information & Comm Engg": "ts",
				"Faculty of Technology": "ts",
				"Faculty of Architecture & Planning": "ts",
				"Faculty of Science & Humanities": "ts",
				"Faculty of Management Studies": "ts"
			},
			"UNIVERSITY  SPORTS BOARD": {
				"ChairmanAnna University Sports Board": "ts",
				"Deputy Chairman,Anna University Sports Board": "ts",
				"Assistant Director - I": "ts",
				"Assistant Director - II": "ts",
				"Assistant Director - III": "ts"
			},
			"HEADS OF THE DEPARTMENTS College of Engineering Campus": {
				"Civil Engineering": "ts",
				"Mechanical Engineering": "ts",
				"Industrial Engineering": "ts",
				"Manufacturing Engineering": "ts",
				"Mining Engineering": "ts",
				"Printing Technology": "ts",
				"Electrical & Electronics Engineering": "ts",
				"Electronics & Communication Engg": "ts",
				"Computer Science & Engineering": "ts",
				"Information Science and Technology": "ts",
				"Mathematics": "ts",
				"Physics": "ts",
				"Chemistry": "ts",
				"English": "ts",
				"Geology": "ts",
				"Media Sciences": "ts",
				"Management Studies": "ts",
				"Medical Physics": "ts"
			},
			"Alagappa College of Technology Campus": {
				"Chemical Engineering": "ts",
				"Ceramic Technology": "ts",
				"Textile Technology": "ts",
				"Biotechnology": "ts",
				"Leather Technology": "ts",
				"Food Technology": "ts",
				"Applied Science & Technology": "ts"
			},
			"School of Architecture and Planning Campus": {
				"Architecture": "ts",
				"Planning": "ts"
			},
			"Madras Institute of Technology Campus": {
				"Aerospace Engineering": "ts",
				"Automobile Engineering": "ts",
				"Production Technology": "ts",
				"Instrumentation Engineering": "ts",
				"Information Technology": "ts",
				"Computer Technology": "ts",
				"Electronics Engineering": "ts",
				"Rubber & Plastics Technology": "ts",
				"Computer Centre": "ts"
			},
			"Heads  of Divisions": {
				"Structural Engineering": "ts",
				"Soil Mechanics & Foundation Engineering": "ts",
				"Transportation Engineering": "ts",
				"Central Workshop": "ts",
				"Engineering Design": "ts",
				"Refrigeration & Air conditioning": "ts",
				"Internal Combustion Engineering Division": "ts",
				"High Voltage": "ts",
				"Power Systems Engineering": "ts"
			},
			"Directors  (CEG, ACT, SAP)": {
				"Centre for Professional Development Education": "ts",
				"Centre for Academic Courses": "ts",
				"Centre for Admissions": "ts",
				"Ramanujan Computing Centre": "ts",
				"Centre for Affiliation of Institutions": "ts",
				"AU-FRG Institute for CAD/CAM": "ts",
				"Centre for Biotechnology": "ts",
				"Centre for Climate Change & Adaptation": "ts",
				"Crystal Growth Centre": "ts",
				"Centre for Distance Education": "ts",
				"Educational Multimedia Research Centre": "ts",
				"Institute of Energy Studies": "ts",
				"Centre for Entrance Examination": "ts",
				"Logistics Centre": "ts",
				"Centre for Environmental Studies": "ts",
				"Centre for Faculty Development": "ts",
				"Health Centre": "ts",
				"Centre for International Affairs": "ts",
				"Knowledge Data Centre": "ts",
				"Centre for Nano Science & Technology": "ts",
				"Institute for Ocean Management": "ts",
				"Institute of Remote Sensing": "ts",
				"Centre for Research": "ts",
				"Centre for Student Affairs": "ts",
				"University Library": "ts",
				"Centre for Water Resources": "ts",
				"Centre for University & Industry Collaboration": "ts",
				"AU-TVS": "ts",
				"Alumni Affairs": "ts",
				"Building Technology Centre": "ts",
				"Institute of Catalysis and Petroleum Tech(ICPT)": "ts",
				"Centre for Development of Tamil in Engg & Tech": "ts",
				"Centre for Disaster Mitigation and Management": "ts",
				"Centre for Empowerment of Women": "ts",
				"Centre for Entrepreneurship Development": "ts",
				"Centre for Human Settlements": "ts",
				"Centre for Intellectual Property Rights": "ts",
				"Centre for Medical Electronics": "ts",
				"Centre for Potential with Excellence in Environmental Science": "ts",
				"Centre for Technology Development and Transfer": "ts",
				"Food Technology": "ts"
			},
			"Deputy Directors": {
				"Academic Courses - I": "ts",
				"Academic Courses - II": "ts",
				"Academic Courses - III": "ts",
				"Research": "ts",
				"Student Affairs - I": "ts",
				"Student Affairs - II": "ts",
				"Student Affairs - III": "ts",
				"Affiliation of Institutions - I": "ts",
				"Affiliation of Institutions - II": "ts",
				"International Affairs": "ts",
				"Network Administration": "ts",
				"Web Administration": "ts",
				"Admissions": "ts",
				"Entrance": "ts",
				"Distance Education ñ I": "ts",
				"Distance Education ñ II": "ts",
				"Distance Education ñ III": "ts",
				"University Industry Collaboration ñ I": "ts",
				"University Industry Collaboration ñ II": "ts",
				"Knowledge Data Centre": "ts"
			},
			"Important Officers": {
				"Prof. & Estate Officer": "ts",
				"Professor of Planning & Development": "ts",
				"Secretary TNEA/ TANCA": "ts",
				"Legal Officer": "ts",
				"Professor ñ Syndicate": "ts",
				"Finance Officer": "ts",
				"Administrator,Main Guest House": "ts",
				"AEE (Civil)": "ts",
				"AEE (Elec.)": "ts",
				"Deputy Registrar (Personnel)": "ts",
				"Deputy Registrar (C&G)": "ts",
				"Assistant Registrar (Salaries)": "ts",
				"Assistant Registrar (Purchase)": "ts"
			},
			"OFFICE OF THE DEAN ñ CEG Direct Line: 2230 1357": {
				"Dean": "ts",
				"Assistant Registrar": "ts",
				"AC-30 Superintendent": "ts",
				"AC-10 / 20 Superintendent": "ts",
				"Tapal Section": "ts",
				"AC 14": "ts",
				"AC 13": "ts",
				"AC 22": "ts",
				"AC 21": "ts",
				"AC 31": "ts",
				"Students Section Superintendent": "ts",
				"SM 11": "ts",
				"SM 13": "ts",
				"SM 14": "ts",
				"PA to Dean": "ts",
				"Student Section": "ts",
				"Conference Hall": "ts",
				"Xerox": "ts",
				"Student Advisor ñI": "ts",
				"Student Advisor ñII": "ts",
				"Ladies Rest Room": "ts",
				"CEM Cell": "ts",
				"TDP": "ts"
			},
			"OFFICE OF THE DEAN ñ A.C. Tech. Direct  Line: 2235 2642": {
				"Dean": "ts",
				"Steno To Dean": "ts",
				"Dean Office ñ Superintendent": "ts",
				"Dean Office": "ts"
			},
			"OFFICE  OF THE  DEAN ñ SAP Direct Line: 2235 2341": {
				"Dean": "ts",
				"PA to Dean": "ts",
				"Office ñ Superintendent": "ts",
				"Office": "ts"
			},
			"OFFICE  OF THE  DEAN ñ MIT Direct  Line: 2223 2403": {
				"Dean": "ts",
				"PA to Dean": "ts"
			},
			"ADMINISTRATIVE  SECTIONS": {
				"P.P.Section Superintendent": "ts",
				"P.P.Section": "ts",
				"P.R.10 Superintendent": "ts",
				"P.R.10 Section": "ts",
				"P.R.20 Superintendent": "ts",
				"P.R.20 Section": "ts",
				"P.R.30 Superintendent": "ts",
				"P.R.30 Section": "ts",
				"P.R.40 Superintendent": "ts",
				"P.R.40 Section": "ts",
				"P.R.50 Superintendent": "ts",
				"P.R.50 Section": "ts",
				"P.R.60 Superintendent": "ts",
				"P.R.60 Section": "ts",
				"F.A.10 Superintendent": "ts",
				"F.A.10 Section": "ts",
				"F.A.20 Superintendent": "ts",
				"F.A.20 Section": "ts",
				"F.A.30 Superintendent": "ts",
				"F.A.30 Section": "ts",
				"F.A.40 Superintendent": "ts",
				"F.A.40 Section": "ts",
				"F.A.50 & 60 Superintendent": "ts",
				"F.A.50 & 60 Section": "ts",
				"F.A.70 Superintendent": "ts",
				"F.A.70 Section": "ts",
				"F.A.80 Superintendent": "ts",
				"F.A.80 Section": "ts",
				"F.A.90 Superintendent": "ts",
				"F.A.90 Section": "ts",
				"Legal Section": "ts",
				"Syndicate Section": "ts",
				"Steno to Finance Officer": "ts",
				"P&D Section Superintendent": "ts",
				"P&D Section": "ts"
			},
			"OFFICE OF THE CONTROLLER OF EXAMINATIONS (AFFILIATED COLLEGES)": {
				"COE": "ts",
				"ACOE ñ I": "ts",
				"ACOE ñ II": "ts",
				"ACOE (Zones)": "ts",
				"Deputy Controller, COE": "ts",
				"Deputy Controller, Distance Education": "ts",
				"Zonal Officer Zone ñ I": "ts",
				"Zonal Officer Zone ñ II": "ts",
				"Zonal Officer Zone ñ III": "ts",
				"Senior Special Officer, Finance & Legal": "ts",
				"P.A to COE": "ts",
				"COE Waiting Hall": "ts",
				"Server Room": "ts",
				"Computer Room": "ts",
				"Printer Room": "ts",
				"Confidential Room": "ts",
				"Stationery": "ts",
				"Multipurpose Hall": "ts",
				"C ñ 10 Superintendent": "ts",
				"C ñ 10 Section (UG)": "ts",
				"C ñ 10 Section(PG)": "ts",
				"Audit Section": "ts",
				"C ñ 60 Superintendent": "ts",
				"C ñ 60 Section": "ts",
				"C ñ 40 Superintendent": "ts",
				"C ñ 40 Section": "ts",
				"C ñ 50 Superintendent": "ts",
				"Tapal Section": "ts",
				"C ñ 30 Superintendent": "ts",
				"C ñ 30- A-Section": "ts",
				"C ñ 30- B-Section": "ts",
				"C ñ 20 Asst. Registrar": "ts",
				"C ñ 20 - Superintendent": "ts",
				"Deputy Registrar": "ts",
				"C ñ 20 Section": "ts",
				"Committee Room": "ts",
				"Reception": "ts",
				"Transcript Section ñ 1": "ts",
				"Transcript Section ñ 2": "ts",
				"Distance Education": "ts",
				"Zone I - Office": "ts",
				"Zone II - Office": "ts",
				"Zone III - Office": "ts",
				"EQP": "ts",
				"Lab": "ts",
				"Conference Hall": "ts",
				"Confidential Room ñI": "ts",
				"Confidential Room ñII": "ts",
				"Confidential Room ñIII": "ts"
			},
			"OFFICE OF THE ADDITIONAL CONTROLLER OF EXAMINATIONS (UNIVERSITY DEPARTMENTS) (CEG, ACT, MIT & SAP)": {
				"Additional Controller (CEG)": "ts",
				"Deputy Controller (CEG) (UG / FT)": "ts",
				"Deputy Controller (UG part time)": "ts",
				"Deputy Controller (PG)": "ts",
				"Deputy Controller (Data Processing Section)": "ts",
				"Superintendent (Administration)": "ts",
				"Superintendent (PG )": "ts",
				"Superintendent (UG )": "ts",
				"Tapal": "ts",
				"Stores ñI": "ts",
				"Accounts": "ts",
				"Steno": "ts",
				"Assistant": "ts",
				"Stores ñII": "ts",
				"Record Room": "ts",
				"ARMS": "ts",
				"Office (PG)": "ts",
				"Office (UG)": "ts",
				"Scrutiny Hall": "ts"
			},
			"AUDIT SECTIONS": {
				"Deputy Director, Concurrent Audit": "ts",
				"Deputy Director, Internal Audit II": "ts",
				"Assistant Director, Internal Audit": "ts",
				"Concurrent Audit Section": "ts",
				"Internal Audit Section-I": "ts",
				"Internal Audit Section-II": "ts",
				"Audit Co-ordination Section, Superintendent": "ts",
				"Audit Co-ordination Section": "ts"
			},
			"University Admin - GENERAL": {
				"Tapal Section": "ts",
				"Academic Hall": "ts",
				"Security": "ts",
				"Store Room": "ts"
			}
		},
		"Faculty of Civil Engineering": {
			"DEPARTMENT OF CIVIL ENGINEERING": {
				"Head of the Department": "ts",
				"P.A to HOD": "ts",
				"Office": "ts",
				"Conference Hall": "ts"
			},
			"STRUCTURAL ENGINEERING": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr.G.M.Samuel Knight": "ts",
				"Dr.M.Sekar": "ts",
				"Dr.E.Arumugam": "ts",
				"Dr.K.Nagamani": "ts",
				"Associate Professor": "ts",
				"Dr.R.Senthil": "ts",
				"Dr.K.C.Pazhani": "ts",
				"Dr.K.P.Jaya": "ts",
				"Dr.C.Umarani": "ts",
				"Dr.K.Chinnaraju": "ts",
				"Assistant Professor": "ts",
				"Mr.P.K.Prabhu Kumar (Sr.Gr.)": "ts",
				"Dr.S.Greeshma (Sr.Gr))": "ts",
				"Dr.V.Ponmalar": "ts",
				"Ms.R.Vidjeapriya(Sr.Gr)": "ts",
				"Dr.H.Jane Helena": "ts",
				"Laboratories": "ts",
				"Structural Engineering Lab": "ts",
				"Structural Dynamics Lab": "ts",
				"Technical Asst.(SML)": "ts",
				"Technical Asst.(SDL)": "ts",
				"CAD Lab": "ts",
				"Anti room(SEL)": "ts",
				"General": "ts",
				"Visiting Professor Room": "ts",
				"Meeting Hall": "ts",
				"Karikalan Hall": "ts",
				"Rajarajan Hall": "ts",
				"Library": "ts",
				"Office": "ts"
			},
			"SOIL MECHANICS & FOUNDATION ENGINEERING": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr.K.Ilamparuthi": "ts",
				"Dr. V.K.Stalin": "ts",
				"Associate Professor": "ts",
				"Dr.K.Premalatha": "ts",
				"Dr.M.Muttharam": "ts",
				"Assistant Professor": "ts",
				"Dr.S.Raheema Shabeen": "ts",
				"Laboratories": "ts",
				"Computer Lab (Soil)": "ts",
				"Advanced Soil Testing Laboratory": "ts",
				"Annex Laboratory": "ts",
				"Triaxial Room": "ts",
				"General": "ts",
				"Library": "ts",
				"Meeting room": "ts",
				"Office": "ts"
			},
			"CENTRE FOR WATER RESOURCES": {
				"Director": "ts",
				"Dr.N.K.Ambujam": "ts",
				"Professor Emeritus": "ts",
				"Dr.R.Sakthivadivel": "ts",
				"Professor": "ts",
				"Dr.S.Ravichandran": "ts",
				"Dr.Usha Natesan": "ts",
				"Dr.B.V.Mudgal": "ts",
				"Dr.M.Krishnaveni": "ts",
				"Associate Professors": "ts",
				"Dr .Madhavi Ganesan": "ts",
				"Mr.R.Rajkumar": "ts",
				"Dr.R.Balamurugan": "ts",
				"Dr.R.Saravanan": "ts",
				"Assistant Professor Senior Grade": "ts",
				"Dr.Carolin Arul (Sr.Gr)": "ts",
				"Assistant Professors": "ts",
				"Mr.M.S.Karthikeyan": "ts",
				"Dr.K.Ramesh": "ts",
				"Dr.E.Arun Babu": "ts",
				"Dr.Soorya Vennila": "ts",
				"Dr.V.Lenin Kalyana Sundaram": "ts",
				"Mr.V.Ramji": "ts",
				"Ms.P.Supriya": "ts",
				"General": "ts",
				"Teaching Fellows": "ts",
				"P.S.to Director": "ts",
				"Office": "ts",
				"Office-Supdt": "ts",
				"Mr.M.Mariyappan": "ts",
				"Project Room I": "ts",
				"Project Room II": "ts",
				"Project Room III": "ts",
				"Research Scholar": "ts",
				"Library": "ts",
				"Hydraulics Lab": "ts",
				"Water net Lab": "ts",
				"GIS Lab": "ts",
				"Wet Chemistry Lab": "ts",
				"P.G.Lab - Instrumentation Room": "ts",
				"Seminar Hall": "ts",
				"Soil Science Lab": "ts"
			},
			"INSTITUTE FOR OCEAN MANAGEMENT Direct Line: 2220 0159": {
				"Director": "ts",
				"Professor": "ts",
				"Dr.R.Ramesh": "ts",
				"Laboratories": "ts",
				"Ecotoxicology Lab": "ts",
				"Radiochemistry Lab": "ts",
				"Instruments (GC) Lab": "ts",
				"Research Scholar Computer Lab ñ I": "ts",
				"Water Chemistry Lab": "ts",
				"Research Scholar Computer Lab ñ II": "ts",
				"GIS ñ Lab (ICM)": "ts",
				"General": "ts",
				"Visiting Faculty Room": "ts",
				"Steno": "ts",
				"Office": "ts",
				"Technical Staff Room ñ I": "ts",
				"Technical Staff Room ñ II": "ts",
				"Former Directorís Room": "ts",
				"Library": "ts",
				"Koodal Hall": "ts",
				"IOM-Dana Bergh Building": "ts",
				"Seminar Hall": "ts",
				"Lab": "ts"
			},
			"CENTRE FOR ENVIRONMENTAL STUDIES Direct line: 2235 4296": {
				"Director": "ts",
				"Professor": "ts",
				"Dr .K.Thanasekaran": "ts",
				"Dr .N.Vasudevan": "ts",
				"Dr.S.Kanmani": "ts",
				"Dr.A.Navaneetha Gopalakrishnan": "ts",
				"Associate Professor": "ts",
				"Dr .K.Palanivelu": "ts",
				"Dr .K.Kurian Joseph": "ts",
				"Dr.S.Ganapathy Venkata Subramanian": "ts",
				"Dr .S.Amalraj": "ts",
				"Assistant Professor": "ts",
				"Mr.S.Karthikeyan (Sr.Gr)": "ts",
				"Dr.A.Merline Sheela (Sr.Gr)": "ts",
				"Ms.B.Mani Mekalai": "ts",
				"Mr.G.Dhinagaran": "ts",
				"Ms.R.Arulmozhi": "ts",
				"Laboratories": "ts",
				"Analytical Lab": "ts",
				"Process Lab": "ts",
				"Marine Lab": "ts",
				"Tool Room": "ts",
				"Micro - Biology Lab": "ts",
				"Computer Lab": "ts",
				"Research Lab": "ts",
				"Modelling Lab": "ts",
				"Project Lab": "ts",
				"Air Pollution Lab": "ts",
				"Unit Operation Lab": "ts",
				"General": "ts",
				"Steno to Director": "ts",
				"Office": "ts",
				"Muthian Auditorium": "ts",
				"Library": "ts",
				"Conference Hall": "ts",
				"Faculty Room": "ts"
			},
			"INSTITUTE OF REMOTE SENSING Direct Line: 2230 1197 / 2235 2166 (Fax)": {
				"Director": "ts",
				"Dr.S.S.Ramakrishnan": "ts",
				"Dr.D.Thirumalaivasan": "ts",
				"Dr.R.Vidhya": "ts",
				"Chair Professor": "ts",
				"Dr.S.Kaliappan": "ts",
				"Associate Professor": "ts",
				"Dr.C.Udhayakumar": "ts",
				"Mr.E.Velappan": "ts",
				"Dr.K.Srinivasaraju": "ts",
				"Dr.R.Murugasan": "ts",
				"Dr.M.Shanmugam": "ts",
				"Assistant Professor": "ts",
				"Dr.S.Jayalakshmi": "ts",
				"Mr.K.Srinivasan": "ts",
				"Mrs.M.Navamuniyammal": "ts",
				"Mrs.R.Kanmani Shanmuga Priya": "ts",
				"Laboratories": "ts",
				"Survey Lab": "ts",
				"Electronic Surveying Lab": "ts",
				"Photogrammetry Lab - I": "ts",
				"Photogrammetry Lab - II": "ts",
				"Digital Photogrammetry Lab": "ts",
				"GIS Lab": "ts",
				"Microwave Remote Sensing Lab": "ts",
				"GPS Processing Lab": "ts",
				"R&D Project Lab-I (Flood Lab, First Floor)": "ts",
				"R&D Project Lab-II (Bhuvan, First Floor)": "ts",
				"R&D Project Lab-III (Second Floor South Side)": "ts",
				"R&D Project Lab-IV (Second Floor North Side)": "ts",
				"General": "ts",
				"Assistant Registrar": "ts",
				"Office (Administration)": "ts",
				"Office (Academic)": "ts",
				"Security": "ts",
				"Steno to Director": "ts",
				"Conference Hall": "ts",
				"Auditorium": "ts",
				"C-Star Lab": "ts",
				"C-Star Office": "ts"
			},
			"TRANSPORTATION ENGINEERING": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr .S.Lakshmi": "ts",
				"Associate Professor": "ts",
				"Dr.G.Umadevi": "ts",
				"Dr.K.Gunasekaran": "ts",
				"Assistant Professor": "ts",
				"Dr.G.Malarvizhi": "ts",
				"Laboratories": "ts",
				"Traffic & Computer Laboratory": "ts",
				"Highway Laboratory": "ts",
				"General": "ts",
				"Visiting Professor": "ts",
				"Visiting Faculty": "ts",
				"Division Office": "ts",
				"Division Record Room": "ts",
				"Cabin 1 & 2": "ts",
				"Cabin 3 & 4": "ts",
				"Library": "ts",
				"Faculty Room (Highway Lab)": "ts",
				"Highway Store Room": "ts"
			},
			"CENTRE FOR DISASTER MITIGATION AND MANAGEMNT": {
				"Director": "ts",
				"Steno": "ts",
				"Computer Lab": "ts",
				"Seismology Lab": "ts"
			},
			"BUILDING TECHNOLOGY CENTRE": {
				"Director": "ts",
				"Office": "ts",
				"Security": "ts"
			}
		},
		"Faculty of Mechanical Engineering": {
			"FACULTY OF MECHANICAL ENGINEERING Faculty Chairperson - 7581 / 9489 DEPARTMENT OF MECHANICAL ENGINEERING": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.S.Sampathkumar": "ts",
				"General": "ts",
				"P.A. to H.O.D": "ts",
				"H.O.D Office Superintendent / Assistant": "ts",
				"Ph.D., M.S. (By Research)P.G. (F.T & P.T) SectionU.G. (P.T) Section": "ts",
				"U.G (F.T) Section": "ts",
				"Research Scholars / Guest FacultyS.M.E. Office-Bearers Room / U.G. Library": "ts",
				"Henry Maudslay Hall": "ts"
			},
			"CENTRAL WORKSHOP": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr.L. Karunamoorthy": "ts",
				"Dr.S. Rajendra Boopathy": "ts",
				"Associate Professor": "ts",
				"Dr.S. Balasivanandha Prabu": "ts",
				"Dr.V.S. Senthil Kumar": "ts",
				"Dr.S.Senthil Kumaran": "ts",
				"Dr.M.Pradeep Kumar": "ts",
				"Assistant Professor": "ts",
				"Mr.K.Thirumavalavan": "ts",
				"Dr.J.Prasanna": "ts",
				"Dr.A.Siddharthan": "ts",
				"Th.D.Samuel Raj": "ts",
				"Tmt.J.Sudha": "ts",
				"Laboratories": "ts",
				"General Foreman / Foreman": "ts",
				"Special Machine Shop": "ts",
				"CAM Lab.": "ts",
				"Machine Shop Lab.": "ts",
				"Basic Workshop Practices Lab.": "ts",
				"Electrical & Electronics Lab.": "ts",
				"Mechatronics Lab.": "ts",
				"General": "ts",
				"Store Keeper": "ts",
				"Division Library": "ts",
				"Conference Hall": "ts",
				"Scanning Electron Microscope Room": "ts",
				"Office (Central workshop)": "ts"
			},
			"STEAM LAB": {
				"Research Scholar": "ts",
				"Lab": "ts"
			},
			"ENGINEERING DESIGN": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr.G.Thanigaiyarasu": "ts",
				"Dr.V.Sundareswaran": "ts",
				"Associate Professor": "ts",
				"Dr.Vela Murali": "ts",
				"Dr.A.Elayaperumal": "ts",
				"Dr.K.Shanmuga Sundaram": "ts",
				"Assistant Professor": "ts",
				"Dr.G.Shibu": "ts",
				"Mr.R.Muruganandan": "ts",
				"Ms.Rashia Begum": "ts",
				"Ms.M.Vasumathi": "ts",
				"Laboratories": "ts",
				"CAD Lab": "ts",
				"NVH Lab": "ts",
				"P.G.CAD Lab": "ts",
				"Dynamics Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Draughtsman": "ts",
				"Store Room": "ts"
			},
			"REFRIGERATION AND AIRCONDITIONING": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr. D.Mohanlal": "ts",
				"Dr.R.Saravanan": "ts",
				"Dr.R.Sethumadhavan": "ts",
				"Assistant Professor": "ts",
				"Mr.P.Balachander": "ts",
				"Mr.V.Kumaresan": "ts",
				"Laboratories": "ts",
				"R & AC Lab (PG)": "ts",
				"R & AC Lab (UG)": "ts",
				"Simulation Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Stores": "ts",
				"Research Scholar Room": "ts",
				"Cryogenic / Psychometric Test Facility": "ts",
				"Linde Hall": "ts"
			},
			"INTERNAL COMBUSTION ENGINEERING DIVISION": {
				"Head of Division": "ts",
				"Professor": "ts",
				"Dr.P.Tamil Porai": "ts",
				"Dr.G.Nagarajan": "ts",
				"Associate Professor": "ts",
				"Dr.N.V.Mahalakshmi": "ts",
				"Dr.K.Balasubramanian": "ts",
				"Assistant Professor": "ts",
				"Dr.D.Ganesh (Sr.Gr)": "ts",
				"Mr.M.R.Swaminathan": "ts",
				"Mr.S.Ragavanantham": "ts",
				"Laboratories": "ts",
				"Simulation Lab": "ts",
				"I.C.Engines Lab": "ts",
				"Wind Tunnel Lab": "ts",
				"I.C.E.Lab Annex": "ts",
				"Fuels Lab": "ts",
				"General": "ts",
				"I.C.E. Office Room": "ts",
				"Research Scholar Room": "ts",
				"Staff Room / Simulation Lab": "ts",
				"Staff Room / Wind Tunnel Lab": "ts",
				"Seminar Hall": "ts",
				"I.C.E.Stores": "ts",
				"Conference Hall": "ts"
			},
			"INSTITUTE FOR ENERGY STUDIES Direct line 2235 3637 (Tele Fax)": {
				"Director": "ts",
				"Professor": "ts",
				"Dr.S.Iniyan": "ts",
				"Dr.R.Sethumadhavan": "ts",
				"Dr.E.Natarajan": "ts",
				"Assistant Professor": "ts",
				"Dr.M.Venkataramanan(Sr.Gr)": "ts",
				"Mr.G.Kumaresan(Sr.Gr)": "ts",
				"Laboratories": "ts",
				"Simulation Lab": "ts",
				"Energy Lab ñ I": "ts",
				"Energy Lab ñ II (Old Auto Lab Building)": "ts",
				"Research Scholar Room": "ts",
				"Research Scholar Room (Steam Lab)": "ts",
				"General": "ts",
				"Office": "ts",
				"Project office": "ts",
				"Library": "ts",
				"Conference Hall": "ts"
			},
			"DEPARTMENT OF INDUSTRIAL ENGINEERING": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.P.Shahabudeen": "ts",
				"Dr.T.Paul Robert": "ts",
				"Dr.P.Malliga": "ts",
				"Dr.R.Raju": "ts",
				"Dr.T.Rameshbabu": "ts",
				"Associate Professor": "ts",
				"Dr.R.Dillibabu": "ts",
				"Dr.R.Baskaran": "ts",
				"Dr.M.Rajmohan": "ts",
				"Dr.A.Gnanavelbabu": "ts",
				"Assistant Professor": "ts",
				"Mr.K.Padmanabhan Panchu": "ts",
				"Ms.V.Kamala": "ts",
				"Others": "ts",
				"Office": "ts",
				"Steno to HOD": "ts",
				"Research Scholar": "ts",
				"Computer Lab": "ts"
			},
			"DEPARTMENT OF MANUFACTURING ENGINEERING": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.V.Jayabalan": "ts",
				"Dr.S.Gowri": "ts",
				"Associate Professor": "ts",
				"Dr.G.Arumaikkannu": "ts",
				"Dr.P.Hariharan": "ts",
				"Dr.A.Azad": "ts",
				"Assistant Professor": "ts",
				"Dr.M.Kanthababu": "ts",
				"Dr.M.Omkumar (Sr.Gr)": "ts",
				"Dr.A.Suresh Babu": "ts",
				"Mr.S.Suthagar": "ts",
				"Dr.G.Sakthinathan": "ts",
				"Laboratories": "ts",
				"CIM Lab": "ts",
				"Material Testing Lab": "ts",
				"Micro Machine Lab": "ts",
				"Nano Material Engineering Lab": "ts",
				"Metrology Laboratory": "ts",
				"CAM Lab": "ts",
				"Advanced Machine Tool Lab": "ts",
				"CAD Lab (Annex)": "ts",
				"General": "ts",
				"HODís Office": "ts",
				"Hall of Guiness 68": "ts",
				"Staff Room": "ts",
				"PG Seminar Hall": "ts",
				"AME Room": "ts",
				"Library": "ts"
			},
			"DEPARTMENT OF MINING ENGINEERING": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr .K.V.Shankar": "ts",
				"Dr .K.Srinivas": "ts",
				"Dr .L.Ajaykumar": "ts",
				"Assistant Professor": "ts",
				"Mr.P.Bala Madeswaran": "ts",
				"Mr.D.Edwin David Raj": "ts",
				"Laboratories": "ts",
				"Computer Lab": "ts",
				"Mineral Processing Lab": "ts",
				"Mine Environment Lab": "ts",
				"Rock Mechanics Lab": "ts",
				"Language Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Seminar Hall": "ts"
			},
			"DEPARTMENT OF PRINTING TECHNOLOGY Direct Line: 2235 3050": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.N.Rajeswari": "ts",
				"Associate Professor": "ts",
				"Dr.K.Senthil Vadivu": "ts",
				"Dr.B.Kumar": "ts",
				"Mr.K.Vipinendran": "ts",
				"Assistant Professor": "ts",
				"Ms.M.Kanchana": "ts",
				"Ms.J.P.Nirmala": "ts",
				"Laboratories": "ts",
				"Q.C Lab": "ts",
				"Finishing Lab": "ts",
				"DTP Lab": "ts",
				"Machine Lab": "ts",
				"Plate making Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Conference Hall": "ts",
				"Stores": "ts",
				"Department Library": "ts",
				"Xerox Room": "ts"
			}
		},
		"Faculty of Electrical and Electronics Engineering": {
			"DEPARTMENT OF ELECTRICAL & ELECTRONICS ENGINEERING": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.B.Umamaheswari": "ts",
				"Associate Professor": "ts",
				"Dr.P.Vanajaranjan": "ts",
				"Dr.P.Lakshmi": "ts",
				"Dr.S.Hosimin Thilagar": "ts",
				"Dr.P.Valsalal": "ts",
				"Dr.S.Chandramohan": "ts",
				"Dr.S.K.Patnaik": "ts",
				"Assistant Professor": "ts",
				"Dr.K.Udayakumar (Sr.Gr)": "ts",
				"Dr.R.Ramesh": "ts",
				"Ms.S.Uma": "ts",
				"Mr.S.GaneshKumar": "ts",
				"Mr.S.Solaimanohar": "ts",
				"Mr.G.Venkatesan": "ts",
				"Mr.K.Rathnakannan": "ts",
				"Mr.N.Radhakrishnan": "ts",
				"Simulation Lab": "ts",
				"Machines Lab": "ts",
				"Nampet Lab": "ts",
				"Control & Instrument Lab": "ts",
				"General": "ts",
				"HOD room": "ts",
				"PA to HOD": "ts",
				"Office": "ts",
				"Conference Hall": "ts",
				"Computer Centre": "ts",
				"Computer Lab": "ts",
				"Professor Appadurai Chair": "ts",
				"TRAís room": "ts",
				"Room No.1": "ts",
				"Store room": "ts",
				"Embedded Systems ñ I": "ts",
				"Embedded Systems ñ II": "ts"
			},
			"HIGH VOLTAGE ENGINEERING": {
				"Head of the Division": "ts",
				"Professor": "ts",
				"Dr.S.Usa": "ts",
				"Associate Professor": "ts",
				"Dr.V.GowriSree": "ts",
				"Assistant Professor": "ts",
				"Mr.C.Pugazhendhi Sugumaran (Sr.Gr)": "ts",
				"Laboratories": "ts",
				"Research Lab": "ts",
				"Dielectric Lab": "ts",
				"CAD Simulation Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Computer Centre": "ts",
				"Seminar Hall": "ts",
				"Control Cubicle": "ts"
			},
			"POWER SYSTEM ENGINEERING": {
				"Head of the Division": "ts",
				"Associate Professor": "ts",
				"Dr. R.P. Kumudini Devi": "ts",
				"Dr.G.Uma": "ts",
				"Mr.S.Muthu Kumar": "ts",
				"Mrs.K.Latha": "ts",
				"Assistant Professor": "ts",
				"Dr.A.Kavitha(Sr.Gr)": "ts",
				"Dr.P.Somasundram": "ts",
				"Dr.V.Senthil Kumar": "ts",
				"Mrs.V.Gomathi": "ts",
				"Mrs.S.V.Anbuselvi": "ts",
				"Laboratories": "ts",
				"Power Electronics Lab": "ts",
				"Simulation Lab (PED)": "ts",
				"Power Lab": "ts",
				"Simulation Lab (PS)": "ts",
				"Power System Lab": "ts",
				"Microprocessor Lab": "ts",
				"UG PS Simulation Lab": "ts",
				"General": "ts",
				"Office / Staff Room": "ts",
				"Store Room": "ts",
				"E-Library": "ts"
			}
		},
		"Faculty of Information and Communication Engineering": {
			"DEPARTMENT OF ELECTRONICS & COMMUNICATION ENGINEERING Direct  Line: 2230 1139": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.N.Kumaravel": "ts",
				"Dr.S.Shanmugavel": "ts",
				"Dr.P.V.Ramakrishnan": "ts",
				"Dr.S.Muttan": "ts",
				"Dr.Y.V.Ramanarao": "ts",
				"Associate Professor": "ts",
				"Dr.S.Shenbagadevi": "ts",
				"Dr.M.Meenakshi": "ts",
				"Dr.K.Malathy": "ts",
				"Dr.D.Sridharan": "ts",
				"Mrs.G.Geetha": "ts",
				"Mrs.N.Vijaya": "ts",
				"Dr.S.Nirmaladevi": "ts",
				"Dr.M.A.Bhagyaveni": "ts",
				"Dr.P.Sakthivel": "ts",
				"Assistant Professor": "ts",
				"Dr.M.Sasikala": "ts",
				"Dr.R.Seshasayanan": "ts",
				"Dr.N.Ramadass": "ts",
				"Dr.V.Jawahar Senthil Kumar": "ts",
				"Dr.P.Nirmal Kumar": "ts",
				"Dr.O.Uma Maheshwari(Sr.Gr)": "ts",
				"Mr.T.Laxmikandan(Sr.Gr)": "ts",
				"Dr.C.M.Sujatha(Sr.Gr)": "ts",
				"Dr.S.Poonguzhali(Sr.Gr)": "ts",
				"Mrs.T.Manimekalai(Sr.Gr)": "ts",
				"Mrs.V.Pushpalatha": "ts",
				"Mrs.J.Durgadevi": "ts",
				"Mrs.J.Kamala": "ts",
				"Mr.R.Seetharaman": "ts",
				"Mrs.M.Shanmugapriya": "ts",
				"Mr.K.Praveen": "ts",
				"Mrs.R.Sittalachoumy": "ts",
				"Dr.K.Gunaseelan": "ts",
				"Laboratories": "ts",
				"Devices & Circuits Lab": "ts",
				"Communication System Lab": "ts",
				"Computer Lab": "ts",
				"DSP Lab": "ts",
				"VLSI LAB": "ts",
				"Optical Communication Lab": "ts",
				"Medical Electronics Lab": "ts",
				"Applied Electronics Lab": "ts",
				"Satellite Research Lab": "ts",
				"Satellite Communication Lab": "ts",
				"Biomedical Engineering Lab": "ts",
				"Integrated Electronics Lab": "ts",
				"General": "ts",
				"HOD Office": "ts",
				"Office": "ts",
				"Conference Hall": "ts",
				"Mini Auditorium": "ts",
				"Maxwell Auditorium": "ts",
				"Stores": "ts",
				"Staff Room - I": "ts",
				"Staff Room - II": "ts",
				"TRAs": "ts",
				"Visiting Professor": "ts",
				"Visiting Faculty": "ts",
				"Teaching Fellow": "ts"
			},
			"DEPARTMENT OF COMPUTER SCIENCE AND ENGINEERING Direct Line: 2230 1579": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.K.S.Easwarakumar": "ts",
				"Dr.C.Chellappan": "ts",
				"Dr.T.V.Geetha": "ts",
				"Dr.T.V.Gopal": "ts",
				"Dr.Arul Siromoney": "ts",
				"Associate Professor": "ts",
				"Dr.S.Valli": "ts",
				"Dr.D.Manjula": "ts",
				"Dr.A.P.Shanthi": "ts",
				"Assistant Professor": "ts",
				"Ms.S.Sudha (Sr.Gr)": "ts",
				"Ms.Rajeswari Sridhar (Sr.Gr)": "ts",
				"Dr.G.S.Mahalakshmi (Sr.Gr)": "ts",
				"Mr.T.Raghuveera (Sr.Gr)": "ts",
				"Dr.V.Vetriselvi": "ts",
				"Dr.S.Bose": "ts",
				"Dr.R.Baskaran": "ts",
				"Dr.P.Geetha Palanisamy": "ts",
				"Dr. Madhan Karkey": "ts",
				"Ms.Arokia Xavier Annie": "ts",
				"Ms.Angelin Gladston": "ts",
				"Ms.B.L.Velammal": "ts",
				"Ms.S.Renugadevi": "ts",
				"Dr.D.Shiloah Elizabeth": "ts",
				"Mr.K.Selvamani": "ts",
				"Ms.M.Shanmuga Priya": "ts",
				"Ms.P.Velvizhy": "ts",
				"Dr. Mary Anita Rajam (SG)": "ts",
				"Laboratories": "ts",
				"Ground floor Annex Lab": "ts",
				"Ground floor Lab": "ts",
				"First Floor Lab": "ts",
				"DRS Lab": "ts",
				"Second Floor Lab": "ts",
				"Second Floor Annexure Lab": "ts",
				"Technical Staff Room": "ts",
				"Third Floor Lab": "ts",
				"TCS Lab": "ts",
				"Third Floor Annexure Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Steno": "ts",
				"Stores": "ts",
				"Examination Unit": "ts",
				"Library": "ts",
				"Research Scholars Cabin": "ts",
				"Security": "ts",
				"Seminar Hall": "ts"
			},
			"DEPARTMENT OF COMPUTER SCIENCE ENGINEERING": {
				"Project Lab": "ts",
				"Visiting Faculty": "ts",
				"Research Scholarís Room": "ts"
			},
			"DUAL DEGREE ñ DEPARTMENT OF COMPUTER SCIENCE ENGINEERING": {
				"Dual Degree Lab I ( CPDE Bldg)": "ts",
				"Dual Degree Lab II ( CPDE Bldg)": "ts",
				"Server Room ( CPDE Bldg)": "ts"
			},
			"DEPARTMENT OF INFORMATION SCIENCE AND TECHNOLOGY": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.P.Narayanasamy": "ts",
				"Dr.V.Ramachandran": "ts",
				"Dr.Ranjani Parthasarathi": "ts",
				"Dr.A.Kannan": "ts",
				"Dr.Saswati Mukherjee": "ts",
				"Associate Professor": "ts",
				"Dr.G.V.Uma": "ts",
				"Dr.V.Uma Maheswari": "ts",
				"Dr.J.Indumathi": "ts",
				"Dr.S.Sridhar": "ts",
				"Dr.K.Vani": "ts",
				"Dr.S.Swamynathan": "ts",
				"Dr.P.Yogesh": "ts",
				"Assistant Professor": "ts",
				"Dr.M.Vijayalakshmi(Sr.Gr)": "ts",
				"Dr.T.Mala(Sr.Gr)": "ts",
				"Mr.R.Muthuraj": "ts",
				"Ms.S.Bama": "ts",
				"Mr.N.Thangaraj": "ts",
				"Dr.S.Abirami": "ts",
				"Ms.E.Uma": "ts",
				"Ms.P.Geetha": "ts"
			},
			"DIVISION  OF MCA": {
				"Mr.K.Kulothungan(Sr.Gr.)": "ts",
				"Dr.S.Senthilkumar(Sr.Gr.)": "ts",
				"Ms.Indra Gandhi": "ts",
				"Ms.Selvi Ravindran": "ts",
				"Ms.K.Vidya": "ts",
				"Teaching Fellows": "ts"
			}
		},
		"Faculty of Science and Humanities": {
			"DEPARTMENT OF MATHEMATICS Direct  Line: 2220 1800": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr. M. Chandrasekar": "ts",
				"Dr. K. Ekambavanan": "ts",
				"Dr. P. Ganesan": "ts",
				"Dr. T. N. Shanmugam": "ts",
				"Dr. V. Sridharan": "ts",
				"Dr. M. Venkatesan": "ts",
				"Dr. P. Vijayaraju": "ts",
				"Associate Professor": "ts",
				"Dr. Jones Tarcius Doss": "ts",
				"Dr. P. Loganathan": "ts",
				"Dr. Y. Sarada": "ts",
				"Dr. G. Sethuraman": "ts",
				"Dr. D. Arivudainambi": "ts",
				"Dr. J. Baskar Babujee": "ts",
				"Assistant Professor": "ts",
				"Dr. S. Anbarasu (Sr.Gr)": "ts",
				"Dr. P. Devaraj (Sr.Gr)": "ts",
				"Dr. S. V. Subhashini (Sr.Gr": "ts",
				"Dr. R. Cokilavany (Sr.Gr)": "ts",
				"Dr. K. V. Vijayashree (Sr.Gr)": "ts",
				"Dr. K. Sankar": "ts",
				"Dr. Vimala Manivasakan": "ts",
				"Dr. Vimala Ramani": "ts",
				"Visiting Professor": "ts",
				"Dr. K. S. Venkatakrishnan": "ts",
				"General": "ts",
				"Visiting Faculties Room": "ts",
				"TA / TRAís": "ts",
				"Research Scholars Room": "ts",
				"Computer Lab (Main Bldg)": "ts",
				"Computer Lab ( CPDE Bldg)": "ts",
				"Library": "ts",
				"Seminar Hall": "ts",
				"HoD Office": "ts"
			},
			"DEPARTMENT  OF PHYSICS": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.K.Sivakumar": "ts",
				"Dr.A.Ramalingam": "ts",
				"Dr.S.Ganesan": "ts",
				"Dr.P.Aruna": "ts",
				"Dr.N.Victor Jaya": "ts",
				"Dr.K.Chinnakali": "ts",
				"Associate Professor": "ts",
				"Dr.S.Selladurai": "ts",
				"Dr.K.Murali": "ts",
				"Dr.G.Kalpana": "ts",
				"Assistant Professor": "ts",
				"Dr.J.Velmurugan": "ts",
				"Dr.K.Vishista(Sr.Gr)": "ts",
				"Dr.G.Sasikala": "ts",
				"Dr.A.Mahalingam(Sr.Gr)": "ts",
				"Dr.R.Gopalakrishnan": "ts",
				"Dr.G.Bharanidharan": "ts",
				"Dr.A.Jestin Lenus(Sr.Gr)": "ts",
				"Dr.Radha Perumal Ramasamy": "ts",
				"Faculty Room-1": "ts",
				"Faculty Room-2": "ts",
				"Faculty Room-3": "ts",
				"Faculty Room-4": "ts",
				"Faculty Room-5": "ts",
				"Laboratories": "ts",
				"UG.Lab (B.E)": "ts",
				"PG.Lab": "ts",
				"Materials Characterization Lab": "ts",
				"Medical Physics Lab": "ts",
				"Nanomaterials Lab": "ts",
				"Crystal Research Lab": "ts",
				"Holography Lab": "ts",
				"Chaos Lab": "ts",
				"X-Ray & High Pressure Lab": "ts",
				"Laser Lab": "ts",
				"Research Lab - I": "ts",
				"Research Lab - II": "ts",
				"General": "ts",
				"Office": "ts",
				"Library": "ts",
				"Stores": "ts",
				"Physics Auditorium": "ts"
			},
			"DEPARTMENT OF CHEMISTRY ñ CEG": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.V.Sadasivam": "ts",
				"Dr.V.Murugesan": "ts",
				"Dr.M.Palanichamy": "ts",
				"Dr.P.Kannan": "ts",
				"Dr.K.Shanthi": "ts",
				"Associate Professor": "ts",
				"Dr.A.Pandurangan": "ts",
				"Dr.N.Rajendran": "ts",
				"Dr.M.Sarojadevi": "ts",
				"Assistant Professor": "ts",
				"Dr.M.J.Umapathy (Sr.Gr)": "ts",
				"Dr.K.Subramanian (Sr.Gr)": "ts",
				"Dr.D.Sangeetha (Sr.Gr)": "ts",
				"Dr.R.Y.Sheeja (Sr.Gr)": "ts",
				"Dr.S.Ananda Kumar (Sr.Gr)": "ts",
				"Dr.G.R.Rajarajeswari (Sr.Gr)": "ts",
				"Dr.A.Maheswari": "ts",
				"Faculty cabin": "ts",
				"Laboratories": "ts",
				"Research Lab DST-FIST": "ts",
				"Computer Lab": "ts",
				"XRD Lab": "ts",
				"M.Sc Lab": "ts",
				"Research Lab (Dr.A.Pandurangan)": "ts",
				"Instrument Lab": "ts",
				"Chemical Stores": "ts",
				"M.Tech Polymer Lab": "ts",
				"B.E / B.Tech Chem Lab": "ts",
				"Project Lab (Dr.M.Saroja Devi)": "ts",
				"Research Lab- I": "ts",
				"Research Lab- II": "ts",
				"General": "ts",
				"TRAs": "ts",
				"HOD Office Room": "ts",
				"Visiting Faculty Room": "ts",
				"Library": "ts",
				"Hall of 1960": "ts"
			},
			"DEPARTMENT  OF ENGLISH": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.S.P.Dhanavel": "ts",
				"Dr.Premalatha Rajan": "ts",
				"Associate Professor": "ts",
				"Dr.T.Shrimathy Venkatalakshmi": "ts",
				"Dr.S.Soundiraraj": "ts",
				"Assistant Professor": "ts",
				"Dr.Veena Selvam": "ts",
				"Dr.Stars Jasmine": "ts",
				"Dr.P.R.Sujatha Priyadharsini": "ts",
				"Teaching Fellow": "ts",
				"Guest Lecturer": "ts",
				"Lecturer": "ts",
				"Laboratories": "ts",
				"Language Laboratory": "ts",
				"Communication Laboratory": "ts",
				"General": "ts",
				"Office": "ts"
			},
			"DEPARTMENT  OF GEOLOGY": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.R.Nagendra": "ts",
				"Dr.L.Elango": "ts",
				"Dr.S.Sanjeevi": "ts",
				"Dr.Hema Achyuthan": "ts",
				"Associate Professor": "ts",
				"Dr.S.Srinivasalu": "ts",
				"Assistant Professor": "ts",
				"Dr.C.Lakshmi Narasimhan": "ts",
				"Dr.K.Sivaraj": "ts",
				"Dr.T.Subramani": "ts",
				"Laboratories": "ts",
				"Remote sensing": "ts",
				"IC & Microscope": "ts",
				"Hydrogeology modeling": "ts",
				"Economic Micropaleontology": "ts",
				"AAS": "ts",
				"Quaternary Geology & Paleoclimate": "ts",
				"Geochemistry": "ts",
				"Hydrogeology": "ts",
				"Petrology & mineralogy": "ts",
				"Computer work station": "ts",
				"Lab-III": "ts",
				"General": "ts",
				"Office": "ts",
				"Hall of Gems Auditorium": "ts"
			},
			"DEPARTMENT OF MEDIA SCIENCES Direct Line: 2235 1578": {
				"Head of the Department": "ts",
				"Associate Professor": "ts",
				"Dr.I.Arul Aram": "ts",
				"Assistant Professor": "ts",
				"Ms.P.Uma Maheswari": "ts",
				"Ms.V.R.Revathy": "ts",
				"Ms.K.Venkatalakshmi": "ts",
				"Ms.D.Sunitha": "ts",
				"Dr.S.Arulchelvan": "ts",
				"Mr.C.Velayutham": "ts",
				"Ms.R.Lavanya": "ts",
				"Ms.K.Sunitha": "ts",
				"Ms.Bandita Kumar Panda": "ts",
				"Dr.M.Neelamalar": "ts",
				"Laboratories": "ts",
				"Electronics Lab": "ts",
				"Audio Lab / Studio": "ts",
				"Video Lab / Studio": "ts",
				"Editing Lab": "ts",
				"Computer Lab": "ts",
				"General": "ts",
				"Library": "ts",
				"Office": "ts",
				"Gyan Vani F.M.": "ts",
				"Science and Technology Communication Division": "ts"
			},
			"DEPARTMENT OF MEDICAL PHYSICS": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.S.Ganesan": "ts",
				"Dr.P.Aruna": "ts",
				"Associate Professor": "ts",
				"Dr.J.Velmurugan": "ts",
				"Assistant Professor": "ts",
				"Dr.G.Bharanidharan": "ts",
				"Dr.R.Vidya": "ts",
				"Dr.G.J.Bhagavathiammal": "ts",
				"Laboratories": "ts",
				"Diagnostic & Therapeutic Lab": "ts",
				"Optical Biopsy Lab": "ts",
				"Treatment Planning / Simulation Lab": "ts",
				"Laser Lab": "ts",
				"Spectroscopy & Imaging Lab": "ts",
				"General": "ts",
				"Office": "ts"
			}
		},
		"Faculty of Management Science": {
			"DEPARTMENT OF MANAGEMENT STUDIES": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.L.Suganthi": "ts",
				"Dr.G.Rajendran": "ts",
				"Associate Professor": "ts",
				"Dr.M.V.Supriya": "ts",
				"Assistant Professor": "ts",
				"Dr.Hansa Lysander Manohar (AGP)": "ts",
				"Dr.R.Magesh(Sr.Grade)": "ts",
				"Mrs.E.Thenral": "ts",
				"Mrs.A.Thiruchelvi": "ts",
				"Dr.N.Senthil Kumar": "ts",
				"Mr .S.Krishnakumar": "ts",
				"Dr.Jayanth Jacob": "ts",
				"Mr.A.K.Sheik Manzoor": "ts",
				"General": "ts",
				"Visiting Faculty": "ts",
				"Teaching Fellow": "ts",
				"HOD Office": "ts",
				"Reception": "ts",
				"Auditorium": "ts",
				"Computing lab": "ts",
				"Research Scholar Room": "ts",
				"VOF Room": "ts",
				"Library": "ts",
				"Seminar Hall": "ts"
			}
		},
		"Faculty of Technology (ACT Campus)": {
			"DEPARTMENT OF CHEMICAL ENGINEERING Direct Line: 2235 5373": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.M.Velan": "ts",
				"Dr.N.Nagendra Gandhi": "ts",
				"Dr.T.R.Kubendran": "ts",
				"Dr.Lima Rose Miranda": "ts",
				"Associate Professor": "ts",
				"Dr.Rajamaniccam L.Sai": "ts",
				"Dr.N.Balasubramanian": "ts",
				"Dr.K.Narashiman": "ts",
				"Dr.K.Muthukumar": "ts",
				"Assistant Professor": "ts",
				"Dr.P.GomathiPriya(Sr.Gr)": "ts",
				"Dr.N.Partha(Sr.Gr)": "ts",
				"Dr.S.Renganathan": "ts",
				"Dr.K.V.Radha": "ts",
				"A.Brinda Lakshmi": "ts",
				"J.Jayapriya": "ts",
				"Laboratories": "ts",
				"Petroleum Lab": "ts",
				"Process Simulation Lab": "ts",
				"Sophisticated Instruments Lab": "ts",
				"FIST Lab": "ts",
				"Catalysis Lab": "ts",
				"Membrane Lab": "ts",
				"F.M. Lab": "ts",
				"HMT Lab": "ts",
				"PILOT Lab": "ts",
				"MOP Lab": "ts",
				"Petroleum Testing Lab": "ts",
				"Process Control Lab": "ts",
				"EE Lab": "ts",
				"CFD Lab": "ts",
				"Polymer Composite Lab": "ts",
				"Chemistry Lab": "ts",
				"E.M Lab": "ts",
				"Electrochemical Engineering Lab": "ts",
				"Effluent Treatment Lab": "ts",
				"Bio-Chemical Engineering Lab": "ts",
				"EBMPF Lab": "ts",
				"CRE Lab": "ts",
				"Extraction Lab": "ts",
				"Environmental Protection Lab": "ts",
				"General": "ts",
				"Steno to HOD (Chemical)": "ts",
				"HOD Office (Chemical)": "ts",
				"Library": "ts",
				"R.O Plant": "ts"
			},
			"CHEMISTRY DIVISION": {
				"Professor": "ts",
				"Dr.M.Alagar": "ts",
				"Dr.D.Mohan": "ts",
				"Dr.S.Sivanesan": "ts",
				"Assistant Professor": "ts",
				"Dr.T.Sivakumar": "ts",
				"Dr.M.Dharmendira Kumar": "ts"
			},
			"PHYSICS DIVISION": {
				"Physics Lab": "ts"
			},
			"MATHEMATICS  DIVISION": {
				"Professor": "ts",
				"Dr.P.Vivekanandan": "ts",
				"Dr.S.Sadiqbasha": "ts",
				"TRA": "ts"
			},
			"ENGINEERING DIVISION": {
				"Assistant Professor": "ts",
				"Dr.G.Ravikumar": "ts",
				"Mr.V.Pandiyarajan (Sr.Gr)": "ts",
				"Mr.V.Charles Augustin": "ts",
				"Dr.C.Sharmeela (Sr.Gr)": "ts"
			},
			"DEPARTMENT OF CERAMIC TECHNOLOGY (ACT)": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.V.Kamaraj": "ts",
				"Dr.P.Manohar": "ts",
				"Assistant Professor": "ts",
				"Dr.S.Manisha Vidyavathy": "ts",
				"Dr.D.Thenmuhil": "ts",
				"Laboratories": "ts",
				"Processing Lab": "ts",
				"Furnace Lab": "ts",
				"Characterization Lab": "ts",
				"Fabrication Lab": "ts",
				"General": "ts",
				"Steno to HOD": "ts",
				"HOD Office": "ts",
				"Computer Room & Library": "ts",
				"Seminar Hall": "ts",
				"Faculty Room": "ts"
			},
			"A.C TECH WORKSHOP ñ I": {
				"Staff Room": "ts",
				"Carpentry Lab": "ts",
				"Welding Lab": "ts"
			},
			"A.C TECH WORKSHOP ñ II": {
				"I.C Engine Lab": "ts",
				"S.M Lab": "ts",
				"Electrical Lab": "ts",
				"Workshop": "ts",
				"Crystal Growth Lab": "ts"
			},
			"GENERAL FACILITIES": {
				"Raman Auditorium": "ts",
				"Conference Hall ñI (Room No.210)": "ts",
				"Conference Hall ñI (Room No.211)": "ts",
				"Security": "ts",
				"A.C Tech canteen": "ts",
				"Computer Lab (RCC Annex)": "ts"
			},
			"DEPUTY OF CONTROLLER OF EXAMINATIONS (A.C Tech)": {
				"DCOE": "ts",
				"DCOE Office": "ts",
				"Chief Superintendent": "ts"
			},
			"DISTANCE EDUCATION STUDY CENTRE (A.C Tech)": {
				"Co-ordinator ñ I": "ts",
				"Co-ordinator ñ II": "ts",
				"Office": "ts"
			},
			"DEPARTMENT OF TEXTILE TECHNOLOGY": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.M.Madhusoothanan": "ts",
				"Dr.A.Peer Mohamed": "ts",
				"Dr.K.Raghunathan": "ts",
				"Dr.T.Ramesh Chandran Nayar": "ts",
				"Dr .N.Selvakumar": "ts",
				"Associate Professor": "ts",
				"Dr.N.M.Imayathamizhan": "ts",
				"Dr .S.Subramanian": "ts",
				"Assistant Professor": "ts",
				"Dr.V.R.Giri Dev (Sr.Gr)": "ts",
				"Dr.N.Gobi": "ts",
				"Dr.M.Murugesan (Sr.Gr)": "ts",
				"Mr.B.A.Muralidhar": "ts",
				"Dr.R.Neelakandan": "ts",
				"Dr.M.Renuka Devi (Sr.Gr)": "ts",
				"Mr.D.Vijay Kirubakar Raj": "ts",
				"Mr.D.Yuvaraj": "ts",
				"Laboratories": "ts",
				"Spinning lab I": "ts",
				"Spinning lab II": "ts",
				"Weaving lab I": "ts",
				"Weaving lab II": "ts",
				"Knitting lab": "ts",
				"Chemical processing lab I": "ts",
				"Chemical processing lab II": "ts",
				"Testing lab I": "ts",
				"Testing lab III": "ts",
				"Testing lab IV": "ts",
				"Garment lab": "ts",
				"Computer lab": "ts",
				"Class room-Laboratory Annex": "ts",
				"Library": "ts",
				"HOD-Office": "ts"
			},
			"CENTRE FOR BIO-TECHNOLOGY Direct Line: 2235 0772": {
				"Director": "ts",
				"Professor": "ts",
				"Dr.P.Kaliraj": "ts",
				"Dr.R.B.Narayanan": "ts",
				"Dr.P.Gautam": "ts",
				"Dr.K.Sankaran": "ts",
				"Dr.S.Meenakshisundaram": "ts",
				"Associate Professor": "ts",
				"Dr.Usha Antony": "ts",
				"Dr.C.D.Anuradha": "ts",
				"Dr.S.Ramalingam": "ts",
				"Dr.M.Sukumar": "ts",
				"Assistant Professor": "ts",
				"Dr.B.S.Lakshmi(Sr.Gr)": "ts",
				"Ms.G.Nandhini Devi(Sr.Gr)": "ts",
				"Dr.Sharmila Anishetty": "ts",
				"Dr.Radha Ramachandran": "ts",
				"Dr.R.Palpandiraja": "ts",
				"Dr.S.Ashok Kumar": "ts",
				"Ms.J.Jaya Muthu Nagai": "ts",
				"Dr.J.Tamil Selvan": "ts",
				"Ms.T.Kothai,Member Research Staff": "ts",
				"Laboratories": "ts",
				"Instruments Room": "ts",
				"UG / PG Lab ñ I": "ts",
				"Cell Biology Lab": "ts",
				"BTIS ñ In charge": "ts",
				"BTIS ñ Lab": "ts",
				"Bio ñ Chem Lab": "ts",
				"Pharma Lab": "ts",
				"Food Tech Lab": "ts",
				"General": "ts",
				"Directorís Office": "ts",
				"Data Processing Room": "ts",
				"Superintendent": "ts",
				"Finance Section": "ts",
				"Section": "ts",
				"Technical Staff Room": "ts",
				"Library": "ts"
			},
			"CRYSTAL GROWTH CENTRE Direct Line: 2235 2774": {
				"Director": "ts",
				"Professor": "ts",
				"Dr.D. Arivuoli": "ts",
				"Dr.R. Dhanasekaran": "ts",
				"Dr. J. Kumar": "ts",
				"Dr.K. Baskar": "ts",
				"Dr.S. Moorthy Babu": "ts",
				"Dr.S. Narayana Kalkura": "ts",
				"Dr.R. Jayavel": "ts",
				"Assistant Professor": "ts",
				"Dr.M. Chitra": "ts",
				"Dr.P. Thiyagarajan": "ts",
				"Laboratories": "ts",
				"Verneuil Lab": "ts",
				"Class Room": "ts",
				"Solution Growth Lab": "ts",
				"Power Room": "ts",
				"Cylinder Room": "ts",
				"Melt Growth Lab": "ts",
				"MOCVD Lab ñ II": "ts",
				"Microshopy Lab": "ts",
				"Thin Flim Lab": "ts",
				"Crystal Audi": "ts",
				"Gel Growth Lab": "ts",
				"Bio-Crystalization Lab": "ts",
				"HRXRD & PL Lab": "ts",
				"MOCVD Lab-I": "ts",
				"LPE Lab": "ts",
				"SEM Lab": "ts",
				"Chiller Plant Lab": "ts",
				"Nano Characterization Lab": "ts",
				"General": "ts",
				"Office": "ts",
				"Security": "ts",
				"III-V Sem Conductor Lab(ACT)": "ts",
				"Prof.S.Ramasamy": "ts",
				"Prof.M.Rajagopalan": "ts",
				"Puller Control Panel": "ts",
				"Puller Lab": "ts"
			},
			"CENTRE FOR NANO SCIENCE & TECHNOLOGY Direct Line: 2230 1656": {
				"Director": "ts",
				"Assistant Professor": "ts",
				"Dr.S.Kalaiselvam": "ts",
				"Dr.T.Devasena": "ts",
				"Dr.S.B.Sankar": "ts",
				"General": "ts",
				"Office": "ts",
				"Materials Synthesis Laboratory": "ts",
				"Visting Faculty & TRA": "ts"
			}
		},
		"Faculty of Architecture and Planning": {
			"School of Architecture And Planning": {
				"Dean": "ts",
				"PA to Dean": "ts",
				"General": "ts",
				"Office": "ts",
				"Superintendent": "ts",
				"Deputy Controller of Examinations": "ts",
				"QIP-Cell": "ts",
				"Prof.Pithaavadian Hall": "ts",
				"Library": "ts",
				"Conference Hall": "ts",
				"Staff Rest Room": "ts",
				"Stores": "ts",
				"Security": "ts"
			},
			"DEPARTMENT OF ARCHITECTURE": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.Suresh Kuppuswamy": "ts",
				"Dr.Monsingh David Devadas": "ts",
				"Dr.Ranee Maria Leonie Vedamuthu": "ts",
				"Associate Professor": "ts",
				"Mr.S.K.Rajasekaran": "ts",
				"Dr.K.R.Sitalakshmi": "ts",
				"Dr.P.Meenakumari": "ts",
				"Dr.Iyer Vijayalaxmi Kasinath": "ts",
				"Assistant Professor": "ts",
				"Mr.M.Elango": "ts",
				"Ms.R.H.Rukkumany": "ts",
				"Ms.B.Muthulakshmi": "ts",
				"Mr.N.Srinivasan": "ts",
				"Mr.S.Santhakumar": "ts",
				"Ms.G.Beulah Gnana Ananthi": "ts",
				"Ms.R.Rajeswari": "ts",
				"Ms.A.Kavitha": "ts",
				"Mr.S.Saravanan": "ts",
				"Computer Laboratories": "ts",
				"New UG Lab": "ts",
				"Internet Lab": "ts",
				"PG (Digital Architecture) Lab": "ts",
				"PG (Landscape Lab)": "ts",
				"Others": "ts",
				"Smart Class Room 1": "ts",
				"Environmental Lab": "ts",
				"Workshop": "ts"
			},
			"DEPARTMENT  OF PLANNING": {
				"Head of the Department": "ts",
				"Professor": "ts",
				"Dr.Abdul Razak Mohamed": "ts",
				"Assistant Professor": "ts",
				"Dr.S.R.Masilamani(S.G)": "ts",
				"Mr.K.Pratheep Moses": "ts",
				"HOD Office": "ts",
				"Project Room": "ts",
				"Computer Lab": "ts",
				"GIS Lab": "ts"
			}
		},
		"Centres ñ CEG , ACT Campus": {
			"CENTRE FOR ACADEMIC COURSES": {
				"Director": "ts",
				"Deputy Director, Academic Courses I": "ts",
				"Deputy Director, Academic Courses II": "ts",
				"Academic Courses Sections": "ts"
			},
			"CENTRE  FOR RESEARCH": {
				"Director": "ts",
				"Deputy Director": "ts",
				"P.A to Director": "ts",
				"Research Section": "ts",
				"Server Room": "ts"
			},
			"CENTRE FOR STUDENT AFFAIRS": {
				"Director": "ts",
				"Deputy Director": "ts",
				"Students Enquiry": "ts",
				"Chief Superintendent": "ts",
				"Office": "ts"
			},
			"CENTRE FOR AFFILIATION OF INSTITUTIONS": {
				"Director": "ts",
				"Deputy Director ñI": "ts",
				"Deputy Director ñII": "ts",
				"Assistant Registrar": "ts",
				"Office": "ts"
			},
			"CENTRE FOR INTERNATIONAL AFFAIRS": {
				"Director": "ts",
				"Deputy Director": "ts",
				"Advisor": "ts",
				"Language Teacher-I": "ts",
				"Language Teacher-II": "ts",
				"Overseas Professor-I": "ts",
				"Overseas Professor-II": "ts",
				"Reception": "ts",
				"Office": "ts"
			},
			"CENTRE FOR PROFESSIONAL DEVELOPMENT EDUCATION Direct Line: 2220 0964": {
				"Director": "ts",
				"General": "ts",
				"Steno to Director": "ts",
				"Reception": "ts",
				"Special Officer": "ts",
				"Superintendent": "ts",
				"Assistant": "ts",
				"Salaries Section ñ Teaching Establishment": "ts",
				"Bill , STC, Annual Accounts, Budget Section": "ts",
				"Conference Hall": "ts",
				"Remuneration Bill Section": "ts",
				"Fees Collection Section (SSP)": "ts",
				"Smart Card Section": "ts",
				"Smart Card Photo Room": "ts",
				"News Bulletin Section": "ts",
				"Salary Section ñ Non Teaching Establishment": "ts",
				"Seminar Hall": "ts",
				"CCEC and Travel Grant Section": "ts",
				"Security": "ts"
			},
			"CENTRE FOR UNIVERSITY-INDUSTRY COLLABORATION Direct Line: 2220 0599": {
				"Director": "ts",
				"Deputy Director ñ I": "ts",
				"Deputy Director ñ II": "ts",
				"General": "ts",
				"Office": "ts",
				"Steno to Director": "ts",
				"Reception": "ts",
				"Meeting Room": "ts",
				"Faculty Room": "ts"
			},
			"AU-FRG ñ INSTITUTE FOR CAD/CAM Direct Line: 22351991": {
				"Director": "ts",
				"Professor": "ts",
				"Dr.R.Velraj": "ts",
				"Dr.K.Srinivasan": "ts",
				"Dr.C.Jebaraj(Professor of Eminence)": "ts",
				"Associate Professor": "ts",
				"Dr.Latha Nagendran": "ts",
				"Ms.Mira Asha Menon": "ts",
				"Assistant Professor": "ts",
				"Mr.K.Malar Mohan": "ts",
				"General": "ts",
				"Office": "ts",
				"RP Room": "ts",
				"Reception": "ts",
				"AC Plant": "ts",
				"Front Reception / Security": "ts",
				"Server Room": "ts"
			},
			"EDUCATIONAL MULTIMEDIA RESEARCH CENTRE Direct Line: 2230 0105 / 0106": {
				"Director": "ts",
				"Control Room (Television)": "ts",
				"Community Radio (Recording Room)": "ts",
				"Satellite Interacting Terminal": "ts",
				"Producers": "ts",
				"V. Ravi": "ts",
				"A. Raja": "ts",
				"General": "ts",
				"Maintenance Room": "ts",
				"Preview Room": "ts",
				"Security": "ts",
				"Tapes library": "ts",
				"P.A to Director": "ts",
				"EMMRC Office": "ts",
				"Store Room": "ts",
				"Conference Room": "ts",
				"Multimedia Lab": "ts",
				"Cameramen Room": "ts"
			},
			"HEALTH CENTRE": {
				"Director": "ts",
				"Medical Officers": "ts",
				"Consultation Room-I": "ts",
				"Consultation Room-II": "ts",
				"Pharmacy": "ts",
				"Bio-Clinical Lab": "ts",
				"Physiotherapy": "ts",
				"Dressing Room": "ts",
				"Office": "ts",
				"Medical Officers Hall": "ts",
				"Store Room": "ts",
				"Ward": "ts",
				"Ladies Gym": "ts"
			},
			"CENTRE FOR DISTANCE EDUCATION Direct Line: 2230 1315": {
				"Director": "ts",
				"Deputy Director- MBA": "ts",
				"Deputy Director ñ MCA": "ts",
				"Deputy Director ñ MSC": "ts",
				"General": "ts",
				"Superintendent": "ts",
				"Office": "ts",
				"Special Officer": "ts",
				"Set I/VI": "ts",
				"Set II/VII": "ts",
				"Set III/VIII": "ts",
				"Set IV": "ts",
				"Set V": "ts",
				"Visiting Faculty Room": "ts",
				"Conference Hall": "ts",
				"Enquiry": "ts",
				"Record Room": "ts",
				"Book Bank": "ts",
				"Server Room": "ts",
				"Application form issue/ fee collection counter": "ts"
			},
			"LOGISTICS CENTRE": {
				"Director": "ts",
				"Transport Officer": "ts",
				"Office": "ts",
				"Superintendent": "ts"
			},
			"CENTRE FOR CLIMATE CHANGE & ADAPTATION (CWR ANNEX BUILDING)": {
				"Director": "ts",
				"Office": "ts",
				"Conference Room": "ts",
				"Scientist Room": "ts",
				"Modeling Lab": "ts"
			},
			"CENTRE FOR DEVELOPMENT OF TAMIL IN ENGINEERING & TECHNOLOGY": {
				"Director": "ts",
				"Office": "ts"
			},
			"CENTRE FOR EMPOWERMENT OF WOMEN Direct Line: 2235 1626": {
				"Director": "ts",
				"Office": "ts"
			},
			"CENTRE FOR ENTREPRENEURSHIP DEVELOPMENT": {
				"Director": "ts",
				"Office": "ts"
			},
			"CENTRE FOR FACULTY DEVELOPMENT Direct Line: 2230 1692": {
				"Director": "ts",
				"Office": "ts",
				"ANNA EDUSAT Studio": "ts"
			},
			"CENTRE FOR INTELLECTUAL PROPERTY RIGHTS": {
				"Director": "ts",
				"Advisor": "ts",
				"Office": "ts",
				"CIPR Lab ñ I": "ts",
				"CIPR Lab ñ II": "ts"
			},
			"KNOWLEDGE  DATA CENTRE": {
				"Director": "ts",
				"Office": "ts",
				"Data Centre Room": "ts",
				"Conference Room": "ts"
			},
			"CENTRE WITH POTENTIAL FOR EXCELLENCE IN ENVIRONMENTAL SCIENCE": {
				"Director": "ts",
				"Office": "ts"
			},
			"CENTRE FOR HUMAN SETTLEMENTS": {
				"Director": "ts",
				"CHS Room": "ts"
			},
			"CENTRE FOR MEDICAL ELECTRONICS": {
				"Director": "ts",
				"Dr.N.Kumaravel": "ts",
				"Professor": "ts",
				"Dr.S.Muttan": "ts",
				"Associate Professor": "ts",
				"Dr.S.Shenbaga Devi": "ts",
				"Ms.S.Nirmala Devi": "ts"
			},
			"CENTRE FOR TECHNOLOGY DEVELOPMENT AND TRANSFER": {
				"Director": "ts",
				"Superintendent I": "ts",
				"Assistant": "ts",
				"General": "ts",
				"Office": "ts",
				"Visiting Faculty": "ts"
			},
			"AU-TVS CENTRE FOR QUALITY MANAGEMENT": {
				"Director": "ts",
				"Office": "ts",
				"Students Quality Club": "ts",
				"Colloauim": "ts"
			},
			"AU ñ CISCO REGIONAL ACADEMY": {
				"Director": "ts",
				"Laboratories": "ts",
				"CISCO Academic Lab": "ts",
				"DCSE Lab": "ts",
				"HP Research Lab": "ts",
				"General": "ts",
				"Reception": "ts"
			},
			"INSTITUTE OF CATALYSIS AND PETROLEUM TECHNOLOGY": {
				"Director": "ts",
				"Office": "ts"
			},
			"ANNA UNIVERSITY NEWS BULLLETIN Direct Line: 2220 1335": {
				"Co-ordinator": "ts",
				"Office": "ts"
			}
		},
		"Central Facilities and Services": {
			"RAMANUJAN COMPUTING CENTRE": {
				"Director": "ts",
				"Dr.V.Rhymend Uthariaraj": "ts",
				"Professor": "ts",
				"Dr.T.P.Saravanabava": "ts",
				"Dr.K.Murugan": "ts",
				"Associate Professor": "ts",
				"Dr.D.George Washington": "ts",
				"Dr.R.S.Bhuvaneswaran": "ts",
				"Dr.H.Khanna Nehemiah": "ts",
				"Assistant Professor": "ts",
				"Mr.S.Anbuchelian (Sr. Gr.)": "ts",
				"Mr.C.Chinthamani": "ts",
				"Dr.K.P.Mani Anand": "ts",
				"Dr.A.John Prakash": "ts",
				"Mr.S.Lokesh": "ts",
				"Research Scholars Room": "ts",
				"Laboratories": "ts",
				"Advanced Computing Lab": "ts",
				"Browsing Lab": "ts",
				"Services": "ts",
				"Web Updations": "ts",
				"Common Computer Purchase Hall": "ts",
				"Network/Hardware Assistance (Internet Connection)": "ts",
				"VoIP-Telephone Hub Assistance": "ts",
				"Others": "ts",
				"Directorís Office": "ts",
				"Office": "ts",
				"Conference Hall": "ts",
				"KIDS Hall": "ts",
				"Dr.Natesan Hall": "ts",
				"AUBCT": "ts",
				"Security": "ts"
			},
			"ESTATE OFFICE": {
				"Professor & Estate Officer": "ts",
				"A.E.E (Civil ñ 1)": "ts",
				"Steno To EO": "ts",
				"A.E.E ( Electrical)": "ts",
				"Project Assistant": "ts",
				"Superintendent": "ts",
				"Mr.K.Muruganandam, Sr.Tech. Asst (Horti)": "ts",
				"Mr.K.Mathiyalagan, Asst Engineer(Civil)": "ts",
				"Mr.S.Thirunauvukkarasu, Asst. Engineer (Civil)": "ts",
				"Mr.G.Mukkani, Junior Engineer (Civil)": "ts",
				"Mr.K.Azithsingh, Junior Engineer (Civil)": "ts",
				"Mr.A.Kalyanaraman, Junior Engineer (Civil)": "ts",
				"Mr.V.Muthamizhkumaran, Junior Engineer (Civil)": "ts",
				"Ms.M.Thilakavathy Junior Engineer (Civil)": "ts",
				"Mr.B.Ganapathi, Junior Engineer (Electrical)": "ts",
				"Mr.U.Kannan, Junior Engineer (Electrical)": "ts",
				"Electrical Maintenance": "ts",
				"Civil Maintenance": "ts",
				"Security Officer": "ts",
				"M.Asaithambi,Sanitary Inspector": "ts",
				"P&E.O Steno": "ts",
				"AB Section(Office)": "ts",
				"Computer Room": "ts",
				"DB Section": "ts",
				"Drawing Officer": "ts",
				"Tapal Section": "ts",
				"Pump Operator": "ts",
				"Power House": "ts",
				"Electrical Sub Station": "ts",
				"Sewage Plant": "ts"
			},
			"EXAMINATION CENTRE": {
				"Director, Admissions": "ts",
				"Director, Entrance Examinations": "ts",
				"Secretary-TNEA/TANCA": "ts",
				"Deputy Director (Admissions)": "ts",
				"Deputy Director (Entrance Exams)": "ts",
				"Superintendent": "ts",
				"Consultant": "ts",
				"Superintendent (TNEA)": "ts",
				"Superintendent (TANCET)": "ts",
				"Assistant(TANCA)": "ts",
				"Cash Section": "ts",
				"Steno": "ts",
				"OA & Drivers Room": "ts",
				"Bank Counter": "ts",
				"TNEA Updation": "ts",
				"Verification": "ts",
				"Scrutiny In-charge": "ts",
				"Scrutiny - II": "ts",
				"Exam.Centre Annex": "ts",
				"Stores I,II Floor": "ts",
				"Server Room": "ts",
				"Confidential Room": "ts",
				"Counselling Hall ñ I Floor": "ts",
				"Hall ñ II Floor": "ts",
				"Security": "ts",
				"Enquiry Office": "ts"
			},
			"UNIVERSITY LIBRARY Direct Line: 2235 5011 2235 2174": {
				"Director": "ts",
				"University Librarian": "ts",
				"Deputy Librarian": "ts",
				"Computer Room": "ts",
				"Circulation New Counter": "ts",
				"Circulation Counter": "ts",
				"Technical Section": "ts",
				"Acquisition Section": "ts",
				"Closed Reference Room-1": "ts",
				"Closed Reference Room-2": "ts",
				"Reading Hall": "ts",
				"Office": "ts",
				"Book Bank (SC/ST)": "ts",
				"Theses Section": "ts",
				"Binding": "ts",
				"Reading Hall-First floor": "ts",
				"Periodical Section": "ts",
				"Periodical Reading Hall-Current Journals": "ts",
				"Photocopy Section": "ts",
				"Seminar Hall": "ts",
				"Audio Visual Room": "ts",
				"Old Magazines & News papers": "ts",
				"Digital Knowledge Centre - 1": "ts",
				"Digital Knowledge Centre - 2": "ts"
			},
			"UNIVERSITY SPORTS BOARD Direct Line: 2235 5007": {
				"Chairman": "ts",
				"Deputy Chairman ñ I": "ts",
				"Deputy Chairman ñ II": "ts",
				"Asst.Director of Physical Education ñ I": "ts",
				"Asst.Director of Physical Education ñ II": "ts",
				"Asst.Director of Physical Education - III": "ts",
				"Office": "ts",
				"Ladies Gym": "ts",
				"Store Room": "ts",
				"Conference Room": "ts"
			},
			"UNIVERSITY MAIN GUEST HOUSE": {
				"Administrator": "ts",
				"Reception": "ts",
				"Conference Hall": "ts",
				"Room No:1": "ts",
				"Room No:2": "ts",
				"Room No:3": "ts",
				"Room No:4": "ts",
				"Room No:5": "ts",
				"Room No:6": "ts",
				"Room No:7": "ts",
				"Room No:8": "ts",
				"Room No:9": "ts",
				"Room No:10": "ts"
			},
			"ALUMINI ASSOCIATION Direct line: 2230 0111, 2235 1314": {
				"Alumini office": "ts",
				"Guest Rooms": "ts",
				"Secretary Chamber": "ts",
				"Caretaker room": "ts"
			},
			"SC/ST CELL": {
				"Nodal Officer": "ts",
				"Superintendent": "ts"
			},
			"NATIONAL  CADET CORPS": {
				"Comp Tech Coy NCC": "ts",
				"Naval Tech Unit": "ts"
			},
			"NATIONAL SERVICE SCHEME CELL Direct Line: 2230 1795": {
				"Co-ordinator": "ts",
				"Office": "ts"
			},
			"YOUTH  RED CROSS": {
				"Co-ordinator": "ts",
				"Office": "ts"
			},
			"HOSTEL  OFFICES (CEG)": {
				"Executive Warden": "ts",
				"Deputy Warden": "ts",
				"Manager": "ts",
				"Cash Counter": "ts",
				"Boarding Clerk": "ts",
				"Computer Room": "ts",
				"Stores": "ts",
				"Store Keeper": "ts"
			},
			"HOSTEL  OFFICES (ACT)": {
				"Executive Warden": "ts",
				"Office": "ts",
				"Mess": "ts",
				"Deputy Warden": "ts"
			},
			"CEG  -STUDY CENTRE": {
				"Co-ordinator- Set-3,Set-4,Set-8": "ts",
				"Co-ordinator-Set-2,Set-7": "ts",
				"Co-ordinator- Set-6": "ts",
				"Co-ordinator-Set-1,Set-5": "ts",
				"Supervisor": "ts",
				"Enquiry": "ts"
			},
			"A.C.Tech  -STUDY CENTRE": {
				"Co-ordinator I": "ts",
				"Co-ordinator II": "ts",
				"Office": "ts"
			},
			"GENERAL": {
				"Main Gate": "ts",
				"Kottur Gate": "ts",
				"Main Campus Annex Security (High Ways)": "ts",
				"Record Room(CEG)": "ts",
				"Key Position (CEG)": "ts",
				"Riffle Guard Room": "ts",
				"Administrative Building": "ts",
				"Co-op Society": "ts",
				"Thrift Society": "ts",
				"Vivekanandha Auditorium": "ts",
				"CEG ñ Canteen": "ts",
				"NCC": "ts",
				"NSS": "ts",
				"NAVY": "ts",
				"Swimming Pool": "ts",
				"SBI - Manager": "ts",
				"SBI - Assistant Manager": "ts",
				"SBI - Counter": "ts",
				"Canara Bank": "ts",
				"Post Office (CEG)": "ts",
				"Day Care Centre": "ts",
				"Gurunath Stationary Stores": "ts",
				"Anna Gem Science Park Matriculation School": "ts",
				"Principal": "ts",
				"Office": "ts",
				"Security": "ts"
			}
		}
	}
            
});
@Injectable()
export class FileDatabase {
   dataChange = new BehaviorSubject<FileNode[]>([]);
   get data(): FileNode[] { return this.dataChange.value; }
   constructor() {
      this.initialize();
   }
   initialize() {
      const dataObject = JSON.parse(TREE_DATA);   
      const data = this.buildFileTree(dataObject, 0);
      this.dataChange.next(data);
   } 
   buildFileTree(obj: {[key: string]: any}, level: number): FileNode[] {
      return Object.keys(obj).reduce<FileNode[]>((accumulator, key) => {
         const value = obj[key];
         const node = new FileNode();
         node.filename = key;
         if (value != null) {
            if (typeof value === 'object') {
               node.children = this.buildFileTree(value, level + 1);
            } else {
               node.type = value;
            }
         }
         return accumulator.concat(node);
      }, []);
   }
}

@Component({
  selector: 'app-visitee-hierarchy',
  templateUrl: './visitee-hierarchy.component.html',
  styleUrls: ['./visitee-hierarchy.component.css','../visitorpass-component/visitorpass-component.component.css'],
  providers: [FileDatabase]
})
export class VisiteeHierarchyComponent {

	@Output() stringEventEmitter: EventEmitter<string> = new EventEmitter<string>();

  treeControl: FlatTreeControl<FileFlatNode>;
  treeFlattener: MatTreeFlattener<FileNode, FileFlatNode>;
  dataSource: MatTreeFlatDataSource<FileNode, FileFlatNode>;  
  constructor(database: FileDatabase) {
     this.treeFlattener = new MatTreeFlattener(this.transformer, this._getLevel,
     this._isExpandable, this._getChildren);
     this.treeControl = new FlatTreeControl<FileFlatNode>(this._getLevel, this._isExpandable);
     this.dataSource = new MatTreeFlatDataSource(this.treeControl, this.treeFlattener);
     database.dataChange.subscribe(data => this.dataSource.data = data);
  }
  transformer = (node: FileNode, level: number) => {
     return new FileFlatNode(!!node.children, node.filename, level, node.type);
  }
  private _getLevel = (node: FileFlatNode) => node.level;
  private _isExpandable = (node: FileFlatNode) => node.expandable;
  private _getChildren = (node: FileNode): Observable<FileNode[]> => observableOf(node.children);
  hasChild = (_: number, _nodeData: FileFlatNode) => _nodeData.expandable;

  selectedNodeString : string ="";
  selectedNode;
  isTrue : boolean = true;
  @Input() displayLabel : boolean = true;
  @Input("placeholder") placeHolderText : string = "";
  
  selectNode = (node: FileFlatNode) => {
    this.selectedNode = node;
  }
  selectNodeString = (node: FileFlatNode) => {
	this.selectedNodeString = node.filename;
	this.emitSelectedNodeString();
  }
  emitSelectedNodeString(){
    this.stringEventEmitter.emit(this.selectedNodeString);
  }
  clearSelectedNodeString(){
	  this.selectedNodeString="";
  }
}

